### ISSUE TITLE
Status STLI of the user interface ZTIMEMACHINE missing

### ISSUE THREAD

**Issue by christianguenter2** [abapinho/abapTimeMachine#124]
When executing ZTIMEMACHINE and when pressing any button on the UI I get the message 'Status STLI of the user interface ZTIMEMACHINE missing' and none of the buttons are working for me.
![grafik](https://user-images.githubusercontent.com/17437789/175256395-325c9faa-0543-4b70-b5d5-3b095811ed21.png)
![grafik](https://user-images.githubusercontent.com/17437789/175255351-d40df595-1e3b-41a6-8ba2-e7b4222c52c8.png)

**Comment by christianguenter2** [comment]
With the latest version I no longer get the message, but buttons are still without effect. Is this intended?

**Comment by nununo** [comment]
@christianguenter2 I hope this is fixed now. Please let me know if you have a problem.

**Comment by christianguenter2** [comment]
@nununo Thx for the fix. Time travel in Blame mode works, but in Time Machine mode it doesn't. I'll open a new issue.
