### ISSUE TITLE
Type "IF_T100_DYN_MSG" is unknown

### ISSUE THREAD

**Issue by jaysonwcs** [abapinho/abapTimeMachine#125]
Tried installing abapTimeMachine on the server, but gives me this error when trying to activate.

The ABAP version is 740 (SP 11).
Is there some dependency that is needed beyond that?

![image](https://user-images.githubusercontent.com/7007373/190265663-2a63a07a-e11b-4f78-b712-b49580e8d2b5.png)

**Comment by nununo** [comment]
@jaysonwcs, I'm sorry that I still didn't address this. I had expected to try to solve this much more quickly but I've been busy lately. Your issue did not go unnoticed, though.

**Comment by nununo** [comment]
@jaysonwcs I removed `IF_T100_DYN_MSG` interface from `ZCX_TIMEM`.
Can you please test it again? 
Thanks

**Comment by jaysonwcs** [comment]
I was able to successfully activate the object. Since the error was the activation, I believe the issue can be closed.
Thanks for the fix!
