### ISSUE TITLE
Update PlantUML class diagram

### ISSUE THREAD

**Issue by nununo** [abapinho/abapTimeMachine#43]

**Comment by larshp** [comment]
UML done, https://abaplint.app/stats/abapinho/abapBlame/uml?name=ZCL_BLAME_ASSET_CSS 😄

**Comment by nununo** [comment]
Wow @larshp man this is so awesome! I'll definitely link to this instead of providing my own PlantUML!! Congratulations! You're amazing!

**Comment by nununo** [comment]
Since yours only gives partial relations between individual objects, I decided to still provide the whole class diagram. But I'll add a link to yours too, of course.
