### ISSUE TITLE
linting?

### ISSUE THREAD

**Issue by larshp** [abapinho/abapTimeMachine#80]
Hi Nuno,
If you are interested, consider enabling https://github.com/marketplace/abaplint for this repository

I can open a PR with an initial `abaplint.json` configuration?

**Comment by nununo** [comment]
Hi Lars! I'm definitely interested. I'd love to implement as many checks and automations as possible but I haven't had time lately to learn how to do it.

The PR with the initial configuration is more than welcome! Cheers!

**Comment by larshp** [comment]
I've set the language version to v750 in #82, the code is not v740 compatible as stated in the readme

few findings you can consider if should be fixed,

```abap
./src/zcl_timem_dynpro.clas.abap[12, 9]                - Variable "i_dynnr" not used (unused_variables) [E]
./src/zcl_timem_gui_viewer.clas.abap[48, 9]            - Variable "io_handler" not used (unused_variables) [E]
./src/zcl_timem_gui_viewer.clas.abap[78, 26]           - Variable "size" not used (unused_variables) [E]
./src/zcl_timem_object_prog_includes.clas.abap[56, 35] - Variable "name" not used (unused_variables) [E]
./src/zcl_timem_object_prog.clas.abap[34, 35]          - Variable "name" not used (unused_variables) [E]
./src/zcl_timem_vrsd.clas.abap[158, 5]                 - Add ORDER BY (select_add_order_by) [E]
./src/ztimemachine.prog.abap[5, 7]                     - Variable "vrsd" not used (unused_variables) [E]
```

**Comment by nununo** [comment]
Implemented in #82

**Comment by nununo** [comment]
@larshp I no longer remember why I chose v750 instead of v740. What would be the simplest way to use Abaplint to check abapTimeMachine against v740? Create a new temp branch and update `abaplint.json`? Or is there a simpler way?

**Comment by nununo** [comment]
@larshp, I believe Abaplint is wrongly flagging `io_handler` as an unused variable in method `zcl_timem_gui_viewer->register_events()`:
https://github.com/abapinho/abapTimeMachine/runs/2974937627

But if you look at the code, it is actually being used:
https://github.com/abapinho/abapTimeMachine/blob/974655d14ceb57a2097137163a80d12fc5454b69/src/zcl_timem_gui_viewer.clas.abap#L108

Can you look into this? It's the last Abaplint error I'm getting ;-)

btw, I wanted to open this issue in the abaplint repository but tbh I'm not sure in which one this should go.

**Comment by larshp** [comment]
thanks, yea, it was a bug

try again, just push another commit

**Comment by nununo** [comment]
Linting is now working. I believe this can be closed. Now it can be used to help make the code compatible with v740sp02. Issue #87 will take care of it.
