### ISSUE TITLE
Compability 740: RAISE EXCEPTION TYPE MESSAGE

### ISSUE THREAD

**Issue by g-back** [abapinho/abapTimeMachine#86]
Hi,
this statement is not compatible with a 740 release:

https://github.com/abapinho/abapTimeMachine/blob/974655d14ceb57a2097137163a80d12fc5454b69/src/zcl_timem_vrsd.clas.abap#L100-L102

How would you like to proceed on this? Raise required version to 750 or can the MESSAGE part be removed (I can create a PR for that, if you want), seems that exception handling has to be refactored anyway.

Thanks

P.S.: ah, seems like some of it was discussed in #80

**Comment by larshp** [comment]
also see https://abaplint.app/stats/abapinho/abapTimeMachine/statement_compatibility

**Comment by nununo** [comment]
> also see https://abaplint.app/stats/abapinho/abapTimeMachine/statement_compatibility

That's so amazing @larshp. You're the 🐐 !!

Is there a way to know exactly which statements exactly in abapTimeMachine's code are incompatible with each version? Looking at that chart it seems quite feasible to make it compatible to `v740sp02`.

Cheers

**Comment by g-back** [comment]
There's a lot of todo comments after exception throws in this class, that's why i assumed 🙂

**Comment by nununo** [comment]
> There's a lot of todo comments after exception throws in this class, that's why i assumed 🙂

Ah indeed there are :) But, as far as I remember, most if not all because those exceptions miss proper descriptive texts :)
