### ISSUE TITLE
Dump by passing ZABAPGITFULL as report name 

### ISSUE THREAD

**Issue by rjbhayani** [abapinho/abapTimeMachine#94]
![image](https://user-images.githubusercontent.com/19501487/125802204-21149094-8183-4f83-92e7-2017fa533922.png)

**Comment by nununo** [comment]
Thank you @rjbhayani,

I found the issue. I was using INT2 to store the program line count and this one is so large that it causes an overflow. I have replaced it with INT4. I will try to commit the correction today.

Thanks for finding this!
